### ISSUE TITLE
Show success/failure message on addition of event, article and job

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/frontend.social#113]
Need to show error message when event, job ot article creation fails.
Should show a red coloured toast message.
Also show a green coloured toast message when the operation succeeds.

**Comment by Mayank-jain34** [comment]
I am not able to assign this to myself but I will be working on this.

**Comment by souvikbasu** [comment]
for records, this is how it looks
![image](https://user-images.githubusercontent.com/195256/79027749-39713580-7b42-11ea-81d4-fc29b77e72bb.png)
