### ISSUE TITLE
Profile: sort list of skills based on expertise and years of exp

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/frontend.social#183]
Sort the skills list on the fly while the user sets years of exp and skills rating
Expertise takes precedence over years of exp

**Comment by Mayank-jain34** [comment]
Hey @souvikbasu,

This is how it's looking when the sorting is done on the fly. For me it's looking a little fuzzy I would prefer if sorting is done when user clicks save button. Let me know what you think.
![skills change](https://user-images.githubusercontent.com/21258010/79009737-dbfada00-7b7d-11ea-96d0-8588d32a2747.gif)
