### ISSUE TITLE
Event - make city optional for online events

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/frontend.social#200]

**Comment by srashtisj** [comment]
Changed position of online checkbox and online link. Also, removed the city section if it's online. I think we don't need it if the event is online.

![chrome-capture (1)](https://user-images.githubusercontent.com/7772451/80277299-a91f1d00-870b-11ea-814c-01fb76b398cb.gif)

**Comment by souvikbasu** [comment]
City online meetups would still want to show city names. Can you please bring that city for online events also. Make it optional though
