### ISSUE TITLE
City: create a world map

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/frontend.social#208]
Show avatars on map based on user location

**Comment by souvikbasu** [comment]
Show this map at top of the cities page above the search text box

**Comment by ThPadelis** [comment]
Hi @souvikbasu. I would like to help with this but I need some info. What kind of avatars will these be?

**Comment by souvikbasu** [comment]
The same avatars can be reused as seen on the City page. 
![image](https://user-images.githubusercontent.com/195256/94899150-a0174200-0447-11eb-8d3f-fb6b87301edf.png)

I will share the page design in a while.

If you face any issues, please join the #frontend-social-dev slack channel using this invite: https://join.slack.com/t/shoonya-tech/shared_invite/zt-i783y3rk-5I97wQmTZ~4zchNZdKJs2w
