### ISSUE TITLE
Fix manifest missing file error

### ISSUE THREAD

**Issue by kapilgorve** [shoonyatech/frontend.social#291]
Error while trying to use the following icon from the Manifest: http://localhost:8080/images/android-chrome-192x192.png (Download error or resource isn't a valid image)

**Comment by Mayank-jain34** [comment]
Fixed in this commit (https://github.com/shoonyatech/frontend.social/commit/165fd852fee72261944b8ff0dd118ba4f64ae077#diff-688128be216cc2f753fe641590f2fcd3) so closing this
