### ISSUE TITLE
Event: any admin should be able to change event video room settings

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/frontend.social#359]
e.g. in the below image both the users are admin but only the event creator is able to change room settings.
![image](https://user-images.githubusercontent.com/195256/82956058-9d09d200-9fcd-11ea-8d19-7b6d51f14fa6.png)

**Comment by Mayank-jain34** [comment]
Closed by https://github.com/shoonyatech/frontend.social/pull/367
