### ISSUE TITLE
Course: show github README file as code for a given chapter topic

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/frontend.social#496]
A lot of chapters will not have any code to show.
For such chapters show the readme file from github as is as MD content. This is displayed to the right of the chapter topic video box

![image](https://user-images.githubusercontent.com/195256/94390239-f3ffef00-0106-11eb-947e-59bb224663d4.png)

**Comment by jad837** [comment]
Hi I would like to work on this under hacktoberfest.

**Comment by souvikbasu** [comment]
Sure, since hacktoberfest starts from 1 Oct, please ensure to send the PR on or after that date. Please let me know if you need any assistance with setting up the project on your localhost

**Comment by jad837** [comment]
How can I recreate the same? I am not able to load any of resource.

**Comment by souvikbasu** [comment]
Steps to reproduce:
- Follow the steps in README file to fork the repo and run the project on your localhost
- Once it runs on localhost then go to route http://localhost:8080/learn/course/getting-started-with-angular

You can connect with us on our slack channel for more discussion where we can help you out: https://shoonya-tech.slack.com/messages/CJ6KZLC9M/

**Comment by jad837** [comment]
Hi I was able to recreate issue and what I have found is there are 2 times when the codes are not shown:-
- Some githubcode url have issues when we try to open in the browser
- When there is no code available "No code is available" text is shown
So I would like some clarification in which of the case Github Readme.md needs to be shown


O.T - I am not able to login in the slack workspace for some reason is there any way to invite me on following email jadhavsaurabh037@gmail.com

**Comment by souvikbasu** [comment]
Sent you slack invite. Please check if you got it. So we need to always show the README file as the default content for the code section in a course page. Later there will be a feature to show the actual code in that space which will override the README file content.
"No code is available" is the case when the GitHub repo is not created for that particular course (happens only when the course is in draft state)

**Comment by souvikbasu** [comment]
fixed
