### ISSUE TITLE
Github: Show social links and list of contributors in the README file

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/frontend.social#507]
Need to show two sections in README
* Stay in Touch: for links to slack channel and twitter
* Contributors: like it in shown in Vue page https://github.com/vuejs/vue

![image](https://user-images.githubusercontent.com/195256/94902613-52053d00-044d-11eb-92d6-e910baf774c8.png)

**Comment by dineshsy** [comment]
hi I would like to take this issue.. My idea will be like creating a SVG file in .github folder of the root of the repo.. and then I will use that SVG in img tag of README.md..

Is it fine?

**Comment by souvikbasu** [comment]
Assigned to @dineshsy . The raw file of README at the vuejs repo has the code for it
https://raw.githubusercontent.com/vuejs/vue/dev/README.md

![image](https://user-images.githubusercontent.com/195256/94909244-bf1dd000-0457-11eb-8bc2-4a676e8e4f14.png)

**Comment by souvikbasu** [comment]
fixed
